name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - matplotlib.pyplot
  - geopandas
  - pandas
  - shapely
  - UserDefined
  - cartopy
  - metpy.plots
